version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: fullstack_auth_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fullstack_user
      POSTGRES_PASSWORD: fullstack_pass
      POSTGRES_DB: fullstack_auth_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
