# fly.toml app configuration file generated for fullstack-auth-api on 2025-03-06T19:11:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-auth-api'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
	protocol = 'tcp'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
	NODE_ENV = 'production'
	HOST = '0.0.0.0'
	PORT = 8080