name: Deploy Client to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel
        working-directory: ./packages/client
        run: npm install -g vercel

      - name: Deploy Client
        working-directory: ./packages/client
        env:
          VERCEL_TOKEN: ${{ secrets.CI_VERCEL_TOKEN }}
        run: vercel --prod --yes --token=VERCEL_TOKEN
