name: Deploy API to Fly.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in ./packages/api
        run: ls -R ./packages/api # Check if prisma/ exists

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check Flyctl version
        run: flyctl version

      - name: Install dependencies (Root)
        run: npm install # Installs everything in the root

      - name: Setup Husky
        run: npx husky install # Run from root explicitly

      - name: Deploy to Fly.io
        working-directory: ./packages/api
        run: flyctl deploy --remote-only --config ./packages/api/fly.toml --app fullstack-auth-api --dockerfile packages/api/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
